# Generated by Django 5.2.5 on 2025-08-19 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ceated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
