# Generated by Django 5.2.5 on 2025-11-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ticket.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em Andamento', 'Em Andamento'), ('Fechado', 'Fechado')], default='Aberto', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('A definir', 'A definir'), ('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='A definir', max_length=20, verbose_name='Prioridade')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Resolução (SLA)')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True, verbose_name='Avaliação')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback do Utilizador')),
                ('show', models.BooleanField(default=True, verbose_name='Visível')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.category', verbose_name='Categoria')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.subcategory', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CRIAÇÃO', 'Criação'), ('COMENTÁRIO', 'Comentário'), ('EDIÇÃO', 'Edição'), ('STATUS', 'Mudança de Status'), ('TRANSFERÊNCIA', 'Transferência'), ('CONCLUSÃO', 'Conclusão'), ('EXCLUSÃO', 'Exclusão'), ('AVALIAÇÃO', 'Avaliação')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(help_text='Descreve o evento. Pode ser um comentário, a solução, o motivo da exclusão, etc.', verbose_name='Descrição')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticket.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento do Ticket',
                'verbose_name_plural': 'Eventos dos Tickets',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_pictures/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticket.ticketevent')),
            ],
            options={
                'verbose_name': 'Imagem do Evento',
                'verbose_name_plural': 'Imagens dos Eventos',
            },
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_pictures/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Imagem do Ticket',
                'verbose_name_plural': 'Imagens dos Tickets',
            },
        ),
    ]
