# Generated by Django 5.2.5 on 2025-08-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ceated_date',
            new_name='created_date',
        ),
    ]
