# Generated by Django 5.2.5 on 2025-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_ceated_date_ticket_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
