# Generated by Django 5.2.5 on 2025-09-13 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_email_remove_ticket_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CRIAÇÃO', 'Criação'), ('COMENTÁRIO', 'Comentário'), ('EDIÇÃO', 'Edição'), ('STATUS', 'Mudança de Status'), ('CONCLUSÃO', 'Conclusão'), ('EXCLUSÃO', 'Exclusão')], max_length=20)),
                ('description', models.TextField(help_text='Descreve o evento. Pode ser um comentário, a solução, o motivo da exclusão, etc.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticket.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
