# Generated by Django 5.2.5 on 2025-09-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketevent_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='picture',
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_pictures/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticket.ticket')),
            ],
        ),
    ]
