# Generated by Django 5.2.5 on 2025-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_priority_options_remove_ticket_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback do Utilizador'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐ Péssimo'), (2, '⭐⭐ Ruim'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Bom'), (5, '⭐⭐⭐⭐⭐ Ótimo')], null=True, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('CRIAÇÃO', 'Criação'), ('COMENTÁRIO', 'Comentário'), ('EDIÇÃO', 'Edição'), ('STATUS', 'Mudança de Status'), ('CONCLUSÃO', 'Conclusão'), ('EXCLUSÃO', 'Exclusão'), ('AVALIAÇÃO', 'Avaliação')], max_length=20),
        ),
    ]
