# Generated by Django 5.2.5 on 2025-09-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_description_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Média', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
