# Generated by Django 5.2.5 on 2025-09-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_priority_delete_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Resolução (SLA)'),
        ),
    ]
