# Generated by Django 5.2.5 on 2025-09-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket_closed_date_ticket_sla_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('CRIAÇÃO', 'Criação'), ('COMENTÁRIO', 'Comentário'), ('EDIÇÃO', 'Edição'), ('STATUS', 'Mudança de Status'), ('TRANSFERÊNCIA', 'Transferência'), ('CONCLUSÃO', 'Conclusão'), ('EXCLUSÃO', 'Exclusão'), ('AVALIAÇÃO', 'Avaliação')], max_length=20),
        ),
    ]
