# Generated by Django 5.2.5 on 2025-10-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticketevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True, verbose_name='Avaliação'),
        ),
    ]
