# Generated by Django 5.2.5 on 2025-11-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticket_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('CRIAÇÃO', 'Criação'), ('COMENTÁRIO', 'Comentário'), ('EDIÇÃO', 'Edição'), ('STATUS', 'Mudança de Status'), ('TRANSFERÊNCIA', 'Transferência'), ('CONCLUSÃO', 'Conclusão'), ('EXCLUSÃO', 'Exclusão'), ('AVALIAÇÃO', 'Avaliação'), ('MENÇÃO', 'Menção')], max_length=20),
        ),
    ]
