# Generated by Django 5.2.5 on 2025-11-10 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticketevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_pictures/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticket.ticketevent')),
            ],
        ),
    ]
